name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Run frontend tests
        run: npm test --prefix frontend -- --watchAll=false

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Run backend tests
        run: pytest backend/tests

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - name: Deploy Backend Staging
        run: curl -X POST "${{ secrets.RENDER_STAGING_BACK }}"

      - name: Deploy Frontend Staging
        run: curl -X POST "${{ secrets.RENDER_STAGING_FRONT }}"

  deploy-develop:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Deploy Backend Develop
        run: curl -X POST "${{ secrets.RENDER_DEV_BACK }}"

      - name: Deploy Frontend Develop
        run: curl -X POST "${{ secrets.RENDER_DEV_FRONT }}"
