name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install dependencies
        run: |
          cd frontend
          npm install
  
      - name: Run tests
        run: |
          cd frontend
          npm test

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests (ignore no tests found)
     #   run: pytest || echo "No tests found, skipping..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - name: Deploy Backend Staging
        run: curl -X POST "${{ secrets.RENDER_STAGING_BACK }}"

      - name: Deploy Frontend Staging
        run: curl -X POST "${{ secrets.RENDER_STAGING_FRONT }}"

  deploy-develop:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Deploy Backend Develop
        run: curl -X POST "${{ secrets.RENDER_DEV_BACK }}"

      - name: Deploy Frontend Develop
        run: curl -X POST "${{ secrets.RENDER_DEV_FRONT }}"
