name: Penetration Testing

on:
  schedule:
    # Ejecutar semanalmente los domingos a las 2:00 AM
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - development

jobs:
  penetration-test:
    name: Full Penetration Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Solo en main branch
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        pip install requests urllib3
        
    - name: Run comprehensive security scan
      env:
        TARGET_URL: ${{ github.event.inputs.target_environment == 'staging' && secrets.STAGING_URL || secrets.DEV_URL }}
      run: |
        python SecurityTesting.py --comprehensive --url $TARGET_URL
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: penetration-test-results
        path: |
          security_report_*.json
          security_test_*.log